namespace Orbitstrap.Enums
{
    public enum ThumbnailType
    {
        Avatar,
        AvatarHeadShot,
        GameIcon,
        BadgeIcon,
        GameThumbnail,
        GamePass,
        Asset,
        BundleThumbnail,
        Outfit,
        GroupIcon,
        DeveloperProduct,
        AutoGeneratedAsset,
        AvatarBust,
        PlaceIcon,
        AutoGeneratedGameIcon,
        ForceAutoGeneratedGameIcon,
        Look,
        CreatorContextAsset,
        Screenshot
    }
}